// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog1: dynamic(() => import("./Blog1")),
  cta01: dynamic(() => import("./Cta01")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
